### ISSUE TITLE
 Pygame Discord link is broken

### ISSUE THREAD

**Issue by Notenlish** [pygame-web/pygame-web.github.io#4]
https://pygame-web.github.io/wiki/pygbag/
The page has a discord invite link to pygame's discord server but when you try to join it gives an error message

![image](https://user-images.githubusercontent.com/71970100/187095820-684ef4fd-32ad-4830-a33d-ae795db78a5e.png)

**Comment by pmp-p** [comment]
thanks for the report ! the new link https://discord.gg/s6Hhrh77aq should appear soon
